In [1]:
import pandas as pd
import os
import tensorflow as tf
from tensorflow.keras.utils import to_categorical
from sklearn.model_selection import train_test_split
import keras
from keras.models import Model
from keras.layers import *
from keras import optimizers

Using TensorFlow backend.


In [12]:
df_test=pd.read_csv("/Users/krishrana/Python/mnist-in-csv/test.csv")
df_train=pd.read_csv("/Users/krishrana/Python/mnist-in-csv/train.csv")

labels=df_train.iloc[:, 0]
features=df_train.iloc[:, 1:785]
test=df_test.iloc[:, 0:784]

In [19]:
features=np.array(features)
features=features.reshape(42000, 28, 28, 1)
labels=np.array(labels)
test=np.array(test).reshape(28000, 28, 28,1)

features = features.astype('float32')
test= test.astype('float32')
print(features.shape)
print(test.shape)

(42000, 28, 28, 1)
(28000, 28, 28, 1)


In [20]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.utils import to_categorical

In [38]:
features = features/255
test = test/255

labels=to_categorical(labels, num_classes=10)
print(labels)

[[[1. 0. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[0. 1. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 ...

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [0. 1. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]]]


In [26]:
model=Sequential()
model.add(Conv2D(32, (3,3), activation='relu', input_shape=(features.shape[1:])))
#model.add(Conv2D(32, (3,3), activation='relu'))
model.add(MaxPooling2D(2,2))

model.add(Conv2D(64, (3,3), activation='relu'))
#model.add(Conv2D(64, (3,3), activation='relu'))
model.add(MaxPooling2D(2,2))

model.add(Conv2D(128, (3,3), activation='relu'))
#model.add(Conv2D(128, (3,3), activation='relu'))
model.add(MaxPooling2D(2,2))

model.add(Flatten())
model.add(Dense(500))
model.add(Activation('relu'))
model.add(Dropout(0.25))
model.add(Dense(200))
model.add(Activation('relu'))
model.add(Dropout(0.25))
model.add(Dense(10))
model.add(Activation('softmax'))
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 11, 11, 64)        18496     
_________________________________________________________________
max_pooling2d_4 (MaxPooling2 (None, 5, 5, 64)          0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 3, 3, 128)         73856     
_________________________________________________________________
max_pooling2d_5 (MaxPooling2 (None, 1, 1, 128)         0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 128)              

In [27]:
epochs=25
batch_size=32
adam=optimizers.Adam(lr=0.01)

In [28]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [29]:
model.fit(features, labels, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Train on 33600 samples, validate on 8400 samples
Epoch 1/25
33600/33600 [==============================] - 21s 618us/sample - loss: 0.2911 - acc: 0.9074 - val_loss: 0.1078 - val_acc: 0.9667
Epoch 2/25
33600/33600 [==============================] - 20s 608us/sample - loss: 0.0908 - acc: 0.9727 - val_loss: 0.0966 - val_acc: 0.9720
Epoch 3/25
33600/33600 [==============================] - 22s 640us/sample - loss: 0.0671 - acc: 0.9800 - val_loss: 0.0698 - val_acc: 0.9808
Epoch 4/25
33600/33600 [==============================] - 20s 596us/sample - loss: 0.0546 - acc: 0.9837 - val_loss: 0.0605 - val_acc: 0.9819
Epoch 5/25
33600/33600 [==============================] - 20s 598us/sample - loss: 0.0422 - acc: 0.9868 - val_loss: 0.0553 - val_acc: 0.9850
Epoch 6/25
33600/33600 [==============================] - 22s 669us/sample - loss: 0.0364 - acc: 0.9896 - val_loss: 0.0855 - val_acc: 0.9782
Epoch 7/25
33600/33600 [==============================] - 23s 684us/sample - loss: 0.0327 - acc: 0.9904 -

In [30]:
model.save('mnistNet.pt')

In [34]:
pred=model.predict(test)

In [37]:
print(pred.shape)

(28000, 10)


In [39]:
y = np.argmax(pred, axis=-1)
print(y)

[2 0 9 ... 3 9 2]


In [40]:
prediction=pd.DataFrame(y, columns=['Label']).to_csv('Mnist.csv')